### ISSUE TITLE
Samtools fails to compile on Mac OS Sierra 10.12.6. gcc/clang issue?

### ISSUE THREAD

**Issue by nach0** [samtools/samtools#1177]
Hello. I am trying to compile the latest Samtools (1.10) on Mac OS Sierra 10.12.6 (running on a Mid 2011 iMac, 2.7 GHz i5). I run `./configure` and it doesn’t return any errors (at least that I notice), although I get a weird line at least 3 times in the output, saying `sed: 24: "/^[    ]*VPATH[    ]*=[    ]* ...": bad flag in substitute command: ’t’`
when I run make it fails, returning the following error:

```
    gcc -g -Wall -O2 -I.  -I./lz4  -c -o bam_index.o bam_index.c
    bam_index.c:29:10: fatal error: 'htslib/hts.h' file not found
    #include <htslib/hts.h>
            ^~~~~~~~~~~~~~
    1 error generated.
    make: *** [bam_index.o] Error 1
```

I had a look at config.log and found several instances of an error in clang (such as `argument to '-V' is missing (expected 1 value)` or `unknown argument: '-qversion’`), and they all arise from a command which has an option with the argument `>&5`. For example, the first error arises after the line `gcc -V >&5`, the second one after `gcc -qversion >&5`. To me it looks like a wrong encoding of the arguments, which makes configure write the wrong value. Anyway I am just an amateur, I know just the basics of UNIX and compiling, only the most straightforward cases.

I searched for my issue and [found a clue in StackOverflow](https://stackoverflow.com/questions/20132805/configure-error-with-mac-os-x-10-8-5-xcode-5-0-2-clang-error-argument-to-v). It seems that the gcc compiler used by Mac OS command line tools is not pure gcc but relies on clang (whatever that is) and that is what makes compiling fail in my case. However I wonder why I haven’t found this issue reported by any other Mac OS user.

I see there was already an issue closed related to gcc/clang ([#1107](https://github.com/samtools/samtools/pull/1107)), but I guess it didn’t cover this problem (sorry my knowledge doesn’t reach the point where I understand how gcc/clang interact and are concerned in that issue)

**Comment by jkbonfield** [comment]
I don't have 10.12.6 but do have 10.13.6 (High Sierra) and the release tarball of samtools built using "./configure; make" fine.  It also passes "make check".

The gcc on that system is apple LLVM (clang) 10.0.0.  Use gcc -v to report that.

Is that "bad substitute" flag in the stdout output from configure?  I don't see that.  I do see lots of warnings in config.log (including the aversion one), but that's normal as it tries various compiler options to figure out what works and what doesn't.

Your error looks like it is failing to find the htslib subdirectory.  Did you build from a release tarball or a git clone?  If the latter, did you also clone htslib too (either as a sibling directory or as a subdirectory to samtools)?

For building from the release tarball, which has htslib as a bundled subdirectory, you should find after configure you get a config.mk which defines various htslib location paths.  Something like this:

```
$ grep -i htslib config.mk
HTSDIR = htslib-1.10
include $(HTSDIR)/htslib.mk
include $(HTSDIR)/htslib_static.mk
HTSLIB = $(HTSDIR)/libhts.a
HTSLIB_LIB = $(HTSLIB) $(HTSLIB_static_LIBS)
HTSLIB_LDFLAGS = $(HTSLIB_static_LDFLAGS)
HTSLIB_CPPFLAGS = -Ihtslib-1.10
#HTSLIB_LDFLAGS = -Lhtslib-1.10
#HTSLIB_LIB = -lhts

```

**Comment by nach0** [comment]
Hi, thanks for your response @jkbonfield. And sorry I failed to clarify a couple of things on my first post. **Short answer: I got a config.mk file, but it’s empty**.

My system has gcc: Apple LLVM version 9.0.0 (clang-900.0.39.2). After compiling failed and I found that stackoverflow post pointing to gcc/clang as a culprit, I re-downloaded Apple’s command line tools and re-installed the latest version I could find for my OS (Command_Line_Tools_macOS_10.12_for_Xcode_9.2), I guess you have a newer version and that’s the reason why our gcc versions are different.

I downloaded the latest tarball from http://www.htslib.org/download/ and tried building it, it’s not a git clone.

The `sed: 24: "/^[   ]*VPATH[    ]*=[    ]* ...": bad flag in substitute command: ’t’` message is in the stdout output from configure, yes. It appears 3 times, and now that you mention config.mk (thanks! I didn’t know about this file), I see that this error message appears twice after configure tries to create the config.mk file, first around the middle of the output, and then again at the end (maybe after it failed the first time it tried again at the end?).

```
config.status: creating config.mk
sed: 24: "/^[    ]*VPATH[    ]*=[    ]* ...": bad flag in substitute command: 't'
```

The third occurrence of this message is at the very end of the stdout output, after it tries creating config.h.

I got a config.mk file, but it’s empty, so you’re right with your suspicions. I remember when make first failed I checked for htslib/hts.h and found it inside samtools-1.10/htslib-1.10, so I thought the error should be elsewhere.

**Comment by jkbonfield** [comment]
What is your current working directory?  Could it contain any meta-characters that could confuse the sed script, or even perhaps spaces or tabs may do it.

The sed script in configure doesn't cope with "&" for example in a directory name.  It may also bork on regexp metacharacters such as ^, $, etc.

**Comment by nach0** [comment]
OMG, thank you very much!! So it was the silliest thing. Indeed my working directory had a "&" in the path. My bad for putting the tarballs in my 'Documents/manuals & tutorials' folder (but I always like to keep source for the software I install).

I moved the tarball elsewhere and it all worked fine: configure didn't return the 'bad flag substitute' error, make didn't fail and 'make check' passed without bigger issues (I believe), just a few expected failures.

Sorry to have made such a big deal over such a stupid thing. Maybe it would be good to add a note about this for noobs like me, so we don't open unnecessary threads like this one. Thanks again and sorry for the fuss.
