### ISSUE TITLE
Samtools 1.4.1 install fails.

### ISSUE THREAD

**Issue by swingingsimian** [samtools/samtools#683]
Hi

I have tried this on two systems now and ultimately get the same failure: 

```
>make
...
gcc   -o samtools bam_index.o bam_plcmd.o sam_view.o bam_cat.o bam_md.o bam_reheader.o bam_sort.o bedidx.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o bam2bcf.o bam2bcf_indel.o sample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o faidx.o dict.o stats.o stats_isize.o bam_flags.o bam_split.o bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o bam_quickcheck.o bam_addrprg.o libbam.a libst.a htslib-1.4.1/libhts.a -lz -lm -lbz2 -llzma -lcurl -lcrypto -lncurses -lm -lz  -lpthread
htslib-1.4.1/libhts.a(hfile.o): In function `load_hfile_plugins':
/usr/src/samtools-1.4.1/htslib-1.4.1/hfile.c:809: undefined reference to `hfile_plugin_init_libcurl'
/usr/src/samtools-1.4.1/htslib-1.4.1/hfile.c:812: undefined reference to `hfile_plugin_init_gcs'
/usr/src/samtools-1.4.1/htslib-1.4.1/hfile.c:815: undefined reference to `hfile_plugin_init_s3'
collect2: error: ld returned 1 exit status
Makefile:146: recipe for target 'samtools' failed
make: *** [samtools] Error 1
```
Steps to recreate on docker ubuntu:latest (xenial/16.04):
```
# apt-get update
# apt-get install build-essential
# apt-get install libncurses5-dev
# apt-get install zlib1g-dev
# apt-get install libbz2-dev
# apt-get install liblzma-dev
# apt-get install libcurl3-dev
# apt-get install libssl-dev  # for crypto
# apt-get install wget
# wget https://github.com/samtools/samtools/releases/download/1.4.1/samtools-1.4.1.tar.bz2
# bzip2 -d samtools-1.4.1.tar.bz2
# tar -xvf samtools-1.4.1.tar
# cd samtools-1.4.1
# make                   
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_index.o bam_index.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_plcmd.o bam_plcmd.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o sam_view.o sam_view.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_cat.o bam_cat.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_md.o bam_md.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_reheader.o bam_reheader.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_sort.o bam_sort.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bedidx.o bedidx.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_rmdup.o bam_rmdup.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_rmdupse.o bam_rmdupse.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_mate.o bam_mate.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_stat.o bam_stat.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_color.o bam_color.c
echo '#define SAMTOOLS_VERSION "1.4.1"' > version.h
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bamtk.o bamtk.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam2bcf.o bam2bcf.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam2bcf_indel.o bam2bcf_indel.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o sample.o sample.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o cut_target.o cut_target.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o phase.o phase.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam2depth.o bam2depth.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o padding.o padding.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bedcov.o bedcov.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bamshuf.o bamshuf.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o faidx.o faidx.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o dict.o dict.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o stats.o stats.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o stats_isize.o stats_isize.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_flags.o bam_flags.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_split.o bam_split.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_tview.o bam_tview.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_tview_curses.o bam_tview_curses.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_tview_html.o bam_tview_html.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_lpileup.o bam_lpileup.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_quickcheck.o bam_quickcheck.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_addrprg.o bam_addrprg.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_aux.o bam_aux.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam.o bam.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_import.o bam_import.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o sam.o sam.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o sam_header.o sam_header.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o bam_plbuf.o bam_plbuf.c
ar -csru libbam.a bam_aux.o bam.o bam_import.o sam.o sam_header.o bam_plbuf.o
ar: `u' modifier ignored since `D' is the default (see `U')
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o sam_opts.o sam_opts.c
gcc -g -O2 -I. -Ihtslib-1.4.1  -c -o sam_utils.o sam_utils.c
ar -rcs libst.a sam_opts.o sam_utils.o
gcc   -o samtools bam_index.o bam_plcmd.o sam_view.o bam_cat.o bam_md.o bam_reheader.o bam_sort.o bed
idx.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o bam2bcf.o bam2bcf_indel.o s
ample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o faidx.o dict.o stats.o stats_is
ize.o bam_flags.o bam_split.o bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o bam_quick
check.o bam_addrprg.o libbam.a libst.a htslib-1.4.1/libhts.a -lz -lm -lbz2 -llzma -lcurl -lcrypto -ln
curses -lm -lz  -lpthread
htslib-1.4.1/libhts.a(hfile.o): In function `load_hfile_plugins':
/usr/src/samtools-1.4.1/htslib-1.4.1/hfile.c:809: undefined reference to `hfile_plugin_init_libcurl'
/usr/src/samtools-1.4.1/htslib-1.4.1/hfile.c:812: undefined reference to `hfile_plugin_init_gcs'
/usr/src/samtools-1.4.1/htslib-1.4.1/hfile.c:815: undefined reference to `hfile_plugin_init_s3'
collect2: error: ld returned 1 exit status
Makefile:146: recipe for target 'samtools' failed
make: *** [samtools] Error 1
```

**Comment by swingingsimian** [comment]
btw, this setup works fine with 1.4.

**Comment by daviesrob** [comment]
Annoyingly, it appears that the tarball contains a few files that should not be there, which prevent it from building when you just type `make`.  We will replace it with one that is constructed correctly.

The best work-around is to run `./configure` before `make`.  In fact, you should do this anyway as otherwise the build system will not detect the presence of `libcurl` or `libssl`, and you won't get support for https, Amazon S3 or Google Cloud storage.  See the `INSTALL` files for samtools and htslib for more information.

**Comment by swingingsimian** [comment]
Ah, great thanks.

'configure'  could maybe do with adding here:

   http://www.htslib.org/download/

**Comment by jenniferliddle** [comment]
http://www.htslib.org/download/ has been updated, and this does not appear to be a problem with the latest 1.5 release.
