### ISSUE TITLE
Problem install samtools 0.1.17 (required for Bio::DB::Sam) to Mac OS 10.14.5

### ISSUE THREAD

**Issue by baglenini** [samtools/samtools#1058]
I need to install the Bio::DB::Sam for the HTGTS pipeline (https://github.com/robinmeyers/transloc_pipeline.  As indicated in the README file from Bio::DB::Sam, it only works with samtools up to version 0.1.17..
While I am trying to install it via Shell, it returns the error message at last:

3 warnings generated.

gcc -c -g -Wall  -O2 -fPIC -m64  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=1 -I. bam2depth.c -o bam2depth.o
gcc -g -Wall  -O2 -fPIC -m64  -o samtools bam_tview.o bam_plcmd.o sam_view.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o kaln.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2depth.o -Lbcftools  libbam.a -lbcf -lcurses  -lm -lz
Undefined symbols for architecture x86_64:
  "___ks_insertsort_heap", referenced from:
      _ks_combsort_heap in libbam.a(bam_sort.o)
      _ks_introsort_heap in libbam.a(bam_sort.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [samtools] Error 1
make: *** [all-recur] Error 1

 #### Describe the solution you would like.

As other suggested in other discussion stream for Bio::DB::HTS module, I edited the makefile to add -fPIC to CFLAGS but it still didn't work. 
I am wondering how to overcome the issue... 

Thanks very much!!

**Comment by jmarshall** [comment]
To compile this old version with a recent compiler, you would need to apply 64275b4bd65b94ae426ba94768b19d198dcb7c97.

**Comment by jkbonfield** [comment]
We don't have time to go back and fix old releases.

Is the above the error you get with the old 1.7 code (caused by using a stricter compiler), or the error you see with compiling 1.9 (or develop) as part of Bio::DB::Sam?  The latter is probably where the dev time needs to be spent, but unless we hear otherwise from the Bio::DB::Sam authors we'll assume the incompatibility is somewhere in their code.

**Comment by jmarshall** [comment]
@jkbonfield: Bio-SamTools == Bio::DB::Sam != Bio::DB::HTS. You're thinking of the latter (Rishi et al's), which bundles or uses HTSlib 1.7 / 1.9 / develop / whatever; the OP is looking for the former (Lincoln's), which is atrophied on Samtools 0.1.x.

**Comment by jkbonfield** [comment]
I knew the difference but misread it... Oh! 0.1.17, not my misread of 1.7 (how on earth I read that I don't know - maybe peril sensitive glasses).

0.1.17 wasn't even the latest samtools prior to the rejig.  We're never going to fix that.

@baglenini I believe you have the answer already in @jmarshall's first reply, hence closing this issue.  I would recommend that you switch to using supported software.
